/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package movienightgui;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author deneg
 */
public class ResultPanel extends javax.swing.JPanel {

    private final IDatabase db;
    private final SharedUserModel sharedUserModel;
    private HashMap<Integer, Integer> lobbyVotes;

    /**
     * Creates new form ResultPanel
     * @param db
     * @param sharedUserModel1
     */
    public ResultPanel(IDatabase db, SharedUserModel sharedUserModel1) {
        initComponents();
        this.db = db;
        this.sharedUserModel = sharedUserModel1;
    }
    
    public void init() {
        lobbyVotes = db.getVotes2(sharedUserModel.getLobby());
        ArrayList<Integer> lobbyResults = new ArrayList<>(lobbyVotes.keySet());
        lobbyResults.sort(
                ((m1, m2) -> Integer.compare(lobbyVotes.get(m2), lobbyVotes.get(m1)))
        );
        
        DefaultListModel<String> model = new DefaultListModel<>();
        jList1.setModel(model);
        for (int i = 0; i < lobbyResults.size(); i++) {
            model.addElement(
                    String.format("%d - %s (%d)", i+1, 
                    lobbyResults.get(i), 
                    lobbyVotes.get(lobbyResults.get(i))
            ));
        }
        
        if (lobbyResults.size() > 0) {
            jLabel1.setText("Movie: " + lobbyResults.getFirst());
        }
        
        String username = sharedUserModel.getUsername();
        String ownerUser = db.getBelongingLobbyOwner(username);
        if (username.equals(ownerUser)) {
        	db.emptyLobby(ownerUser);
        	db.emptyInvitations(ownerUser);
        	db.deleteLobby(sharedUserModel.getLobby());
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jList1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jList1.setForeground(new java.awt.Color(51, 102, 0));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("NO MOVIE SELECTED :(");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
